<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Cngn.Sdk</PackageId>
    <Version>1.0.0</Version>
    <Authors>Wrapped CBDC / Convexity</Authors>
    <Description>.NET client for the cNGN API</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/wrappedcbdc/cngn-dotnet</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>cngn;payments;stablecoin</PackageTags>
    <IsPackable>true</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.7.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NBitcoin" Version="10.0.14" />
    <PackageReference Include="libsodium" Version="1.0.22" />
    <None Include="../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
